# Generated by Django 4.1.4 on 2022-12-21 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alcohole', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('volume', models.FloatField(verbose_name='объем')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boozing.drink')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boozing.shop')),
            ],
        ),
        migrations.AddField(
            model_name='drink',
            name='drink_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boozing.drinktype'),
        ),
        migrations.CreateModel(
            name='Degustation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('like', models.BooleanField()),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boozing.drink')),
            ],
        ),
    ]
