# Generated by Django 4.1.4 on 2022-12-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boozing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='boozing.drink'),
        ),
    ]
