# Generated by Django 4.1.4 on 2022-12-23 10:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boozing', '0002_alter_purchase_drink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degustation',
            options={'verbose_name': 'Дегустация', 'verbose_name_plural': 'Дегустации'},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.AlterModelOptions(
            name='drinktype',
            options={'verbose_name': 'Тип напитка', 'verbose_name_plural': 'Тип напитков'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Место покупки', 'verbose_name_plural': 'Место покупок'},
        ),
        migrations.AlterField(
            model_name='degustation',
            name='like',
            field=models.BooleanField(verbose_name='Понравилось'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='alcohole',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент спирта'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boozing.drinktype', verbose_name='Тип напитка'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование напитка'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Цена'),
        ),
    ]
